### ISSUE TITLE
Shop & Product Pages do not Respect Template=Full width

### ISSUE THREAD

**Issue by cancan101** [woothemes/storefront#164]
I have set the Shop and Product pages to use the Full width template but I still see the sidebar.

Setting Template=Full width seems to hide this sidebar for the other pages.

Settings: http://imgur.com/Odg0Flv
Problem pages:
http://imgur.com/kWFQm17
http://imgur.com/NGCVVXN

Working page: http://imgur.com/9DmDgRX

**Comment by jameskoster** [comment]
Please don't post support queries on github.

FYI this is because that shop page is not a 'page' so you cannot apply a template to it this way. It is in fact a redirect to the product post type archive.

If you post on the wordpress.org forums you'll probably get help in achieving this. But if you don't want to touch any code check out this extension which enables you to do his and more: http://www.woothemes.com/products/storefront-woocommerce-customiser/
