### ISSUE TITLE
Quantity Increment style

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/storefront#176]
With our Quantity arrows plugin, the number in the text field is partially hidden

![](http://cld.wthms.co/12Dtv+)

**Comment by jameskoster** [comment]
Probably because the plugin sets a height. Will look into this when I get back.

**Comment by jameskoster** [comment]
Which browser is this? It's looking "ok" here: https://www.dropbox.com/s/2v7nm3mtey3gaxa/Screenshot%202015-05-12%2020.26.11.png?dl=0

**Comment by SiR-DanieL** [comment]
I'm on chrome. It looks wrongly only in the cart, the single product page is fine.

**Comment by jameskoster** [comment]
Hmmm, I don't really want to add any code to Storefront to account for what is essentially a deprecated feature. Ideally, the plugin shouldn't really set a height on the quantity div, that's what's causing the issue here.

For now, a simple CSS snippet should be suffice for anyone requesting help with this.
