### ISSUE TITLE
No Pagination when WooCommerce categories are displaying and a search is performed.

### ISSUE THREAD

**Issue by stuartduff** [woothemes/storefront#180]
When you set the WooCommerce settings to be this below.

Screenshot: http://cld.wthms.co/1hk52

And then perform a product search no pagination or sort functionality displays on the search page.

Screenshot: http://cld.wthms.co/18eAf

**Update:** There is also no pagination on product archives if categories are enabled.

**Comment by EgbertJan** [comment]
Addition: The pagination seems deliberately switched off in the last function in .../inc/woocommerce/template-tags.php. 

If you set the display_type of the mail shop page to categories, also a search with more than a page outpuit wil not show the pagination since, strangly enough, the main shop page template is used for that. Why not a separate seach page/template? The intro text for the search page will probably be different from the text on the shop page. I do use a child theme with just a style.css and a functions.php.

**Comment by jameskoster** [comment]
@stuartduff this should have been fixed in https://github.com/woothemes/storefront/issues/172 Would you mind checking with latest dev on master?

**Comment by jameskoster** [comment]
@stuartduff confirms this is fixed.
