### ISSUE TITLE
Header Image Jumps on Mobile

### ISSUE THREAD

**Issue by DustinHartzler** [woothemes/storefront#252]
Customer in this ticket is having issues with their header image (which in their case is their logo)

Here's what it looks like without the menu expanded:
<img width="389" alt="screen shot 2015-10-22 at 2 25 57 pm" src="https://cloud.githubusercontent.com/assets/2293077/10674461/ebda3ffe-78c8-11e5-9f79-69f44b9b81c0.png">

And here is the header when the menu is selected:
<img width="389" alt="screen shot 2015-10-22 at 2 26 12 pm" src="https://cloud.githubusercontent.com/assets/2293077/10674456/e869e130-78c8-11e5-928c-8f08ad091c75.png">

**Comment by jameskoster** [comment]
This isn't really a bug. I'll explain;

The header image is applied as a background image on `.site-header`. So naturally, when the navigation is expanded that element grows in height and because of the `background-position` of the image, it will move.

There are 2 options:

1. Apply a new `background-position` via customisation.
2. Install Jetpack or the Storefront Site Logo plugin and add the logo properly (much easier and recommended) :-)

**Comment by DustinHartzler** [comment]
Perfect! Thanks for the explanation :)
