### ISSUE TITLE
Add filters for opening column div

### ISSUE THREAD

**Issue by WPprodigy** [woothemes/storefront#256]
What are your thoughts on adding a filter to this line: https://github.com/woothemes/storefront/blob/master/header.php#L50 (and the closing line in the footer).

Just something simple like:
`<?php echo apply_filters( 'storefront_opening_column', '<div class="col-full">' ); ?>`

#### Reasoning:
When child theming, it can be hard to fight against this if you want a full width element on the page. You have to use negative margins, which get messy. And you can see in the SF demo that even the parallax hero has a fault with this: http://cld.wthms.co/xm0U/5vXcEmi8. So the only alternative is to override header.php and footer.php, for the sole purpose of adding that filter.

With a filter there, you can conditionally toggle it and remove/rename the class when needed. This makes it much simpler for child themes to use full width designs without needing to override two templates.

**Comment by jameskoster** [comment]
Hmm I don't really like this so much. That particular class should remain constant and consistent imo. It's used throughout the theme in various places.

Creating a full width element shouldn't be difficult. It involves using negative margins like you say but that shouldn't be a big problem. I'm not seeing the Parallax Hero issue? That space on the right hand side is the scrollbar :p 

You can always hook your element into `storefront_before_content` so that it's outside of the `.col-full` scope. Then there's no need for negative margins at all.

**Comment by WPprodigy** [comment]
Right, it can still be used in other places, just not necessarily wrapped around basically the whole website. The issue comes when you want things to be full width inside of pages/posts. Like this title section: http://cld.wthms.co/10tlQ/xDG6wru7

But I mean, it's not a big deal to have to override the template if the child theme decides to have some full width designs in it. So ¯\_(ツ)_/¯

Idea number 2: What if another class was added there along side `.col-full`? Then you could use CSS and conditionally (using body classes) remove that div's styles.

Regarding the Parallax Hero, 569px to 767px width has an issue for me on all browsers: http://cld.wthms.co/1a4R6/3SAJu1xC

**Comment by jameskoster** [comment]
OK the Parallax Hero thing is a bug (please open an issue xD).

> Idea number 2: What if another class was added there along side .col-full? Then you could use CSS and conditionally (using body classes) remove that div's styles.

You don't need an extra class to do that. You just need a more specific selector :)

Gonna close this as I don't feel it's necessary.
