### ISSUE TITLE
Include TGM

### ISSUE THREAD

**Issue by jameskoster** [woothemes/storefront#257]
I'd like to discuss the idea of including [TGM](https://github.com/TGMPA/TGM-Plugin-Activation) and recommending users install our free plugins on activation.

They all add significant value, and I think most people would install them if they knew about them. A positive experience with these plugins might encourage folks to try our commercial offerings as well.

cc @tiagonoronha @mattyza

**Comment by mattyza** [comment]
@jameskoster - I believe TGM is most useful when the theme/plugin requires other themes/plugins which are paid-for or from a non-standard repository (ie: not WordPress.org).

As our plugins are hosted on WordPress.org (the ones which are "required" to make certain features work -for example, Homepage Control), I feel we could achieve the same or a more elegant result using our own custom code.

We can install WordPress.org plugins using functionality in WordPress core (WooDojo V2 does this) so there isn't much direct need for TGM, in my opinion.

To install a plugin from WordPress.org is all about generating that download link (can be done programmatically). What does TGM offer which assists with this, rather than a few small links of PHP?

Also, a consideration is TGM being allowed in WordPress.org themes. I doubt the Theme Review Team would like TGM, unfortunately.

**Comment by tiagonoronha** [comment]
TGM is allowed in WordPress.org.

I like the idea. It's widely used by many other theme providers and I think we don't really need to reinvent the wheel and code our own.

**Comment by jameskoster** [comment]
TGM is definitely allowed. I've reviewed themes with it :-)

I believe it allows batch plugin installs, so we can give folks a convenient way to install each of them with a single click, straight after activating Storefront. That's the main benefit I suppose - giving folks a more feature rich Storefront experience with minimum effort. The number of free and commercial extensions is growing, we can't highlight them all on the welcome screen. 

Yes, we could code it ourselves but like Tiago says, there's no need to reinvent the wheel. It _might_ be overkill though I agree, it's quite a hefty library.

**Comment by mattyza** [comment]
Thanks for clarifying, @tiagonoronha @jameskoster. :)

Upon reading through the library again, I agree it's quite hefty. This led me to think about the reason the library was created in the first place (I remember when Thomas Griffin launched TGM Plugin Activation). I remember the catalyst being that premium themes were developed poorly and made to *rely* on premium plugins or free plugins.

Storefront doesn't *rely* on anything. :)

If the bulk download is the main reason, perhaps we can repurpose some of the TGM code (or, you know, roll our own) and create a similar result for store owners upon activating Storefront. We'd have more control over what we do in that admin notice (or however it's presented) and not include any unnecessary bloat.

Have y'all tested what TGM Plugin Activation would look like in Storefront? Any screenshots to share, perhaps as a starting point? :)

**Comment by jameskoster** [comment]
nope, haven't installed/tested it yet. You can see some screenshots here: http://tgmpluginactivation.com/screenshots/ They're a bit out of date but you get the idea.

**Comment by mattyza** [comment]
@jameskoster Lets test in a branch and see what this ends up looking like. :)

**Comment by jameskoster** [comment]
Will do when we get around to working on 1.6.

**Comment by BurlesonBrad** [comment]
Hey @jameskoster @mattyza & @tiagonoronha 
Can I throw in a "End User / Semi Coherent / No I'm not Ninja Level but still / Joe Schmoe" opinion?
**_Please don't!_** Y'all know I'm all about supporting Woo and all up in translating rubber-meets-the-road into revenue on both mine and my client's sites, right?

Ok, so if you use Thomas's option _(allowed/not allowed: isn't even on my radar)_, you'd be shooting yourselves in the foot and missing a key point of the *page=storefront-welcome* page.  
##### Pop in TMG and you'll kill the conversions for the _Woo's **Paid** Extensions!_ #####

Keep it the way it is, and people will be forced onto the *storefront-welcome* page where they will be visually prompted to PURCHASE :-) the other plugins. _(and keep the 'free' plugins **below the fold**)_

![enhance](https://cloud.githubusercontent.com/assets/6208757/10861328/52b196f6-7f49-11e5-8f96-2955f4f4386b.png)


I made one of them gist doohickeys for 'ya! Each modification actually has a good deal of thought put into it.  Don't tell anyone, but I'd grin a bit if 'ya put it in the next update.  Plus... in my experience, it'll **boost** your sales as well. WHOOP!

https://gist.github.com/BurlesonBrad/e779bfd99a65355d72d8

**Comment by jameskoster** [comment]
Thanks for your input @BurlesonBrad :-) This is still in the very early discussion stage. There's no plans to actually add the TGM yet.

Did you see that we changed the welcome screen in 1.5.2? The only problem with the welcome screen is that we have no idea how many people actually visit it, nor do we have any way to track that. My worry is that a lot of people are missing out on a lot of goodies by not visiting it at all.

**Comment by BurlesonBrad** [comment]
The blue border gives it a bit of contrast, but.... see the part above? I didn't do any outlines, cool borders, awesome shading or anything like that.  I simply added a **why** to the **what**.  The new one in 1.5.2 looks cool, but the goal is to tell a person **why** they need the _______ and **what** the _______ is going to do for them. 

Lemme do a quick example: **Let's say there's a *foo* for $49 and I told all y'all hardcore coder people about a grunting vagrant that will sync a node with the grep on the command line so that the helium.js would fly up into a cloud based json API and you bought a copy.**   *(no clue wtf i just said, but that's not the point)*  

#### You *buy* because of *why*.  

People buy because of why.  And, when I get a chance, I really want to make sure that I can add a hand in helping sales anytime possible, that's the only reason I changed the text and added buttons on the gist.  

### I don't want people to buy a *thing*, I want people to buy the *why*!

**Comment by jameskoster** [comment]
Good points, I agree. We'll monitor the performance of the new welcome screen and adjust accordingly :)

**Comment by ChangePlaces** [comment]
Firstly I hate the welcome screen and see it as nothing but an annoying advert and never visit it. (Infact, there's a function to remove it from the settings in my child theme as it serves no purpose) 

So... As it's supposed to be a settings page, use it for a settings page. Encourage people to visit it, and often by putting useful settings there. This will show, how, actually, woocommerce has got your back.

Don't want to show the product SKU on product pages? No problem, there's a checkbox to remove it. Want to show category images on category pages? No problem, there's a checkbox to show them. Etc.Make it useful and people will take note of the content on there.

**Comment by jameskoster** [comment]
> So... As it's supposed to be a settings page, use it for a settings page

Our philosophy is that all settings are handled via the Customizer. So this won't fly.

Dunno if you've seen the welcome screen recently but we re-arranged it a bit to include links to the latest Storefront news and featured docs, as well as highlighting free plugins.

Hopefully that makes it less 'shouty / adverty'. At the end of the day though, all of the products we advertise there can potential add value for end users. While they may not be useful to you, our tracking suggests they are useful to a lot of other folks.

**Comment by RiaanKnoetze** [comment]
Why not show the Storefront extensions in the same way as that of WP Job Manager and WooCommerce does by using a separate menu item (it also has the added advantage of being a bit more dynamic)?

As a sidenote, [Storefront Jetpack](https://wordpress.org/plugins/storefront-jetpack/) has the following look which is quite spiffy: http://cld.wthms.co/17oI7/4MPQ9JGm

**Comment by jameskoster** [comment]
I think we'll pass on this for now.
