### ISSUE TITLE
Add support for `site-logo` feature slated for WordPress 4.5

### ISSUE THREAD

**Issue by jameskoster** [woothemes/storefront#340]
If it's included..

**Comment by BurlesonBrad** [comment]
# Holy Daring Fireballs Batman!  
I _thought_ I would give this one a whirl as well, but after reading [this thread](https://make.wordpress.org/core/2016/02/24/theme-logo-support/) my head's a bit spinning.  Definitely no promises on this one, but....  help me digest this if you don't mind:

- [ ] While I appreciate [Nick's Endeavor](https://wordpress.org/plugins/storefront-site-logo/), that one ain't gonna cut it :wink: 
- [ ] The customizer **must** have fields that allow the store owner to **manually define** their logo attributes of height and width else [this error comes up.](https://gtmetrix.com/specify-image-dimensions.html)  _However, do we also include sliders to **adjust** the visible area that they want their logo to "take up" in their site as well?_
- [ ] Must have capacity to scale that one image all the way from mobile all the way up to **HiDPI** / [Retina Display](https://en.wikipedia.org/wiki/Retina_Display) _I know WP will/can handle this, but should their also be some sort of text added (not a tooltip) that spell out & reminds folks to upload their image at 2x their desired ratio?_

Anything else I'm missing under the category of **"understanding scope"**?

**Comment by jameskoster** [comment]
Maybe have a read of this if you want to take a stab at this issue @BurlesonBrad https://make.wordpress.org/core/2016/03/10/custom-logo/

:)

**Comment by BurlesonBrad** [comment]
_...this is why I was dragging my feet a bit_

Now under `/wp-admin/customize.php` there are **two** places for a logo:
One under the heading of **Header** :confused: 
![sf-logo-header](https://cloud.githubusercontent.com/assets/6208757/13901366/91448c9c-edef-11e5-9c2b-40926e082511.png)

And again, under **Site Identity** :anguished: 
![sf-logo-site-identity](https://cloud.githubusercontent.com/assets/6208757/13901367/976b581c-edef-11e5-9b82-5370ce0a01e0.png)

This won't work because it would surely cause confusion for store owners and also has the real tangible possibility of making support ninjas need a shot of whiskey _not just a few_ :beers:!
One of these two has to be removed, while still allowing for backwards capacity for those who **have** already uploaded a logo via the `Header > Logo` option within Jetpack option to not be totally **cornfused.**

**Comment by jameskoster** [comment]
Forgot about that prompt. We can just remove that with 4.5 around the corner.

Backwards compat is built in. If you have a Jetpack logo configured it will continue to display once you update to 4.5 unless you set a logo using the new feature. I'd guess that the Jetpack team have some plans to encourage folks to use the core feature though.
