### ISSUE TITLE
Order review fixed positioning

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/storefront#347]
When the payment form has the class `payment-fixed` this happens:

![](http://cld.wthms.co/1kDGa/56lrg22H+)

I'm not sure how to fix it, but I've seen it in multiple websites using Storefront.

**Comment by jameskoster** [comment]
what's the problem here @SiR-DanieL ?

**Comment by SiR-DanieL** [comment]
The payment form overlaps the footer. The grey part at the bottom of the screenshot is the footer of Storefront. Also you can see a widget on just under the Continue to payment button.

**Comment by jameskoster** [comment]
It overlaps the footer because it sticks to the top of the browser window during scroll. Not really sure of a way around that without disabling the sticky order review feature altogether?

As for the widget, looks like the payment form hasn't finished loading so is still semi-transparent?

There's a section in the FAQ on removing this feature, in case anyone requests it; https://docs.woothemes.com/document/storefront-faq/#section-3

**Comment by SiR-DanieL** [comment]
Ok, if there's a way to disable it in the doc I'm ok with that. Is there an option for this also in one of our customizers?

**Comment by jameskoster** [comment]
Not currently @SiR-DanieL. Please open an issue here; https://github.com/woothemes/storefront-powerpack :)

**Comment by Jamman** [comment]
I think this can be fixed by fixing to the bottom not the top. I got this working in inspector, but it wasn't working in the page.
Example code.
`.woocommerce-checkout .payment-fixed {position: fixed; top: inherit; bottom: 0px;}`
