### ISSUE TITLE
Proposal: Make cart/account page full width by default

### ISSUE THREAD

**Issue by WPprodigy** [woothemes/storefront#379]
When the user is going through the WooCommerce installation wizard, storefront could assign the newly created cart and account pages to the full width template.

This will of course require storefront to be active before WooCommerce is set-up, but I would bet this could help/affect a good number of users.

**Comment by jameskoster** [comment]
We've already spoken about this. It's something we'll look to do in WooCommerce core when the wizard creates the pages. Would you mind opening this issue there instead?

**Comment by WPprodigy** [comment]
Wouldn't this be theme specific though? Not all themes will have the full width template, and it will be named differently quite often. Plus, wouldn't is be strange to check if storefront is activated in WC core?

It should be as easy as updating the page meta, hooked somewhere in the installation process. You can get the page IDs with `wc_get_page_id()`, and then should be able to update the meta with `update_post_meta( $post_id, '_wp_page_template', 'Full width' );`

**Comment by jameskoster** [comment]
My thinking was that WooCommerce would check for a variety of potential template names that we define. Eg.

* full
* fullwidth
* full-width

etc. Most themes that include a full width template use a name like this. If it exists, apply it to the page.

I think any theme that has a full width template should have that template applied to the cart/checkout/myaccount page by default which is why I'm for putting this in WooCommerce core.
