### ISSUE TITLE
Mobile/handheld menu cuts short if its long

### ISSUE THREAD

**Issue by el-presidente** [woothemes/storefront#387]
Tested on different iphones I get a bug on my page www.landhave.dk on my handheld menu - its seems to cut off the end of the menu if its too long.

![img_3490](https://cloud.githubusercontent.com/assets/937382/15092897/6ba1c370-1477-11e6-8606-90922b443766.PNG)

**Comment by el-presidente** [comment]
I'm going to change my site now but its seems to cut off at circa 33 menu items.

**Comment by el-presidente** [comment]
Headers also seems to be misplaced in low resolution: ![screen shot 2016-05-07 at 17 57 35](https://cloud.githubusercontent.com/assets/937382/15093104/3a0cd9c0-147d-11e6-9ed4-2d7120b8c734.png)

**Comment by trussgenius** [comment]
I'm having the same issue.  https://trussgenius.com

**Comment by jameskoster** [comment]
The issue here is that to animate the menu with css we have to use the `max-height` property as it's not possible to animate `height`.

I thought I'd used a large enough value but obviously you guys have pretty lengthy menus!

Until I get an update out, you can increase the max height of your menus with something like this;

`.main-navigation.toggled .handheld-navigation, .main-navigation.toggled .menu>ul:not(.nav-menu) {
max-height: 2500px;
}`

**Comment by el-presidente** [comment]
I went for less menu items as it was too confusing - it results in one more click but is more user friendly.

**Comment by jameskoster** [comment]
Honestly I think that is the best approach. If the menu is too long on handheld devices it really does become confusing quite quickly.

I think I'll close this issue. Having a mobile menu larger than 1750px seems an edge case and is easily fixed with a line of css anyway.
