### ISSUE TITLE
Can't move secondary navigation out of header

### ISSUE THREAD

**Issue by pelachile** [woothemes/storefront#403]
Why doesn't this work?

`remove_action('storefront_header','storefront_secondary_navigation', 50)`

`add_action('storefront_before_content','storefront_secondary_navigation', 60)`

Does it have something to do with the actions being added in storefront-template-functions and storefront-woocommerce-template-functions? 

I can't remove the product search either. Unless I comment out the code in storefront/inc/woocommerce/storefront-woocommerce-template-functions.php.

**Comment by jameskoster** [comment]
This should be posted in support please. Github is for reporting bugs.

I assume you're doing this in a child theme? The issue is that the child theme functions.php file loads before the parent theme. So after you've performed this actions in the child theme, Storefront core simply undoes it when it loads.

Wrap your customisations inside a new function hooked in to `init`.

Cheers
