### ISSUE TITLE
Conflict with WooCommerce Email Customizer

### ISSUE THREAD

**Issue by BFTrick** [woothemes/storefront#450]
There's a bit of CSS in the theme that messes with the [WooCommerce Email Customizer](https://woocommerce.com/products/woocommerce-email-customizer/). And doesn't let it modify the colors in the email header.

``` CSS
table tbody td {
    background-color: #fdfdfd;
}
```

If we remove that property the issue with the Customizer goes away.

That'll fix the issue. I'm not sure what that line of CSS is doing. It's pretty generic which can make overriding it a bit difficult. Can we make it more specific so it doesn't interact weirdly with other plugins?

<img width="776" alt="customize__patrick_s_baller_test_site_ _just_another_wordpress_site" src="https://cloud.githubusercontent.com/assets/1065372/17521916/5f07726a-5e12-11e6-87ba-d3c5678923aa.png">

**Comment by jameskoster** [comment]
> I'm not sure what that line of CSS is doing.

It's applying a background color to table cells ;P Pretty much all themes do this. The difference is that in this case it's being added inline via the Customizer so will overrule any stylesheets.

As the extension is a specific feature, _it_ should overrule the theme styles, not the other way around. In this case it would be perfectly ok the use the `!important` flag, or just add some inline styles in the preview.

I have to wonder why the theme styles are being loaded in the email though. I assume this is only happening in the Customizer, not in the actual email?

**Comment by BFTrick** [comment]
I just tested with Twenty Twelve, Twenty Fifteen, and Twenty Sixteen and they don't have this issue. I assume we're doing something different with Storefront?

> As the extension is a specific feature, it should overrule the theme styles, not the other way around. In this case it would be perfectly ok the use the !important flag, or just add some inline styles in the preview.

I agree - if we have to we can use `!important` to override the default styles. But I'd prefer to write our theme style's in such a way that we don't have to use `!important`. Ex however the Twenty themes are doing it. :)

**Comment by jameskoster** [comment]
> I assume we're doing something different with Storefront?

Indeed we are. :) 

The reason for this issue is that Storefront uses color settings in the Customizer for table styles. Those styles are added inline which is why they're overwriting the email styles. **This is only for the preview**. It certainly shouldn't be happening in the actual email that gets sent.

Seeing as this is an email preview, it shouldn't be including the theme styles at all. Those styles are added in the `Storefront_Customizer` class [here](https://github.com/woothemes/storefront/blob/master/inc/customizer/class-storefront-customizer.php#L29) which makes them a little tricky to remove. Using !important would definitely be easier and in this scenario is a perfectly valid use case - it's important that no theme or plugin styles interact with the email preview.

What do you say?

**Comment by BFTrick** [comment]
Cool so you think adding `!important` to the email customizer plugin would be the best bet?

I'm okay with that if you are. :)

**Comment by jameskoster** [comment]
Yeah I think that'll be safest. I'll open an issue, sure :)
