### ISSUE TITLE
Wording on the comments form

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/storefront#458]
Even if it's not a reply to another comment, it says "Leave a reply", while it should say "Leave a comment"

![](http://cld.wthms.co/1lhi7/4CosPLSh+)

**Comment by opportus** [comment]
Or would that stand as "reply to the post" ?

**Comment by jameskoster** [comment]
Not sure about this. I mean technically you're still replying - just to the post rather than another comment. 

When using the comment-reply script, the title doesn't update when you reply. That means that when you _are_ replying to another comment the title would still be "Leave a comment". That doesn't seem great to me.

Thoughts?

**Comment by SiR-DanieL** [comment]
It makes sense if you see it from the single post page, but if you see the top of the post it says Leave a comment, in the meta. And then at the bottom it says Leave a reply which could be confusing.

We can fix by passing the args in the `comment_form` function: https://codex.wordpress.org/Function_Reference/comment_form#.24args

The indexes `leave_reply` and `leave_reply_to` are exactly for this.

**Comment by jameskoster** [comment]
> The indexes `leave_reply` and `leave_reply_to` are exactly for this.

@SiR-DanieL They only apply if you're not using the comment-reply script ;)

**Comment by jameskoster** [comment]
Seeing as the comment reply script doesn't change the form title I'm going to close this. IMO it's not really worth the hassle to add extra logic to change it.
