### ISSUE TITLE
Fatal error using jetpack ((jetpack mobile theme module on) + storefront theme + storefront powerpack

### ISSUE THREAD

**Issue by boloshabashe** [woothemes/storefront#473]
"Fatal error: Call to undefined function is_woocommerce_activated() in /home/content/n3pnexwpnas02_data02/95/3579695/html/wp-content/plugins/storefront-powerpack/includes/class-sp-admin.php on line 30 "

I found when you use latest storefront theme+ latest jetpack plugin with mobile theme module turned on + storefront new powerpack plugin . You get this error on mobile phones view of your website ..
is this because the storefront powerpack also has a mobile theme option , which conflicts with the jetpack mobile theme option ? or something else , i do not know.
when i deactivate powerpack , storefront & jetpack mobile theme module works perfectly and same is when i deactivate jetpack mobile theme module , powerpack and storefront works perfectly .
i hope i have clarified what i tried to say.

**Comment by jameskoster** [comment]
Thanks for reporting this.

The issue is a little bit complicated but is essentially caused by the fact that the Jetpack mobile theme serves a _different_ theme to handheld devices. Storefront Powerpack _requires_ Storefront, so if you're using a different theme you'll get issues like this.

Honestly, I would suggest _not_ using the mobile theme feature. Storefront is already responsive and the Jetpack mobile theme wont include styling for WooCommerce.

We'll look in to how we can address this in Powerpack in the future.
